"""项目共享 schema 包入口。

这个包负责放 A/B/C 三个成员都需要遵守的数据结构契约。当前已定义
成员 A 输出给成员 B/C 的 UI 候选元素、页面摘要、页面状态和坐标规则，
以及成员 C 输出给成员 B 的动作执行结果协议。
"""

from .document_region import DocumentRegionSummary
from .perception_health import (
    COVERAGE_ADEQUATE,
    COVERAGE_NONE,
    COVERAGE_PARTIAL,
    FALLBACK_NONE,
    FALLBACK_RETRY_WITH_REFOCUS,
    FALLBACK_USE_OCR_ONLY,
    FALLBACK_USE_UIA_ONLY,
    FALLBACK_USE_VLM_VISUAL,
    FLAG_ALL_SHELL,
    FLAG_CANDIDATE_GAP,
    FLAG_NO_CLICKABLE,
    FLAG_NO_INPUT_TARGET,
    FLAG_NO_SEARCH_TARGET,
    FLAG_OCR_LOW_CONFIDENCE,
    FLAG_OCR_SPARSE,
    FLAG_UIA_EMPTY,
    FLAG_UIA_SHELL_DOMINATED,
    HEALTH_DEGRADED,
    HEALTH_HEALTHY,
    HEALTH_UNHEALTHY,
    QUALITY_DEGRADED,
    QUALITY_GOOD,
    QUALITY_POOR,
    PerceptionHealth,
)
from .action_result import (
    ACTION_CLICK,
    ACTION_DOUBLE_CLICK,
    ACTION_HOTKEY,
    ACTION_SCROLL,
    ACTION_TYPE,
    ACTION_WAIT,
    SUPPORTED_EXECUTOR_ACTION_TYPES,
    ActionResult,
    ActionResultSchemaError,
    action_result_from_exception,
    utc_now,
)
from .ui_candidate import (
    COORDINATE_TYPE_NORMALIZED,
    COORDINATE_TYPE_SCREENSHOT_PIXEL,
    SOURCE_MERGED,
    SOURCE_OCR,
    SOURCE_UIA,
    SOURCE_VLM_VISUAL,
    UISchemaError,
    UICandidate,
    bbox_center,
    candidate_from_ocr,
    candidate_from_uia,
    offset_bbox,
    resolve_click_point,
)
from .page_semantics import (
    GOAL_PROGRESS_ACHIEVED,
    GOAL_PROGRESS_BLOCKED,
    GOAL_PROGRESS_IN_PROGRESS,
    GOAL_PROGRESS_NEAR_GOAL,
    GOAL_PROGRESS_NOT_STARTED,
    GOAL_PROGRESS_UNKNOWN,
    PageSemantics,
    PageSemanticsError,
)
from .ui_state import (
    PageSummary,
    ScreenMeta,
    UIState,
    save_screen_meta_json,
    save_ui_state_json,
    screen_meta_artifact_path,
    ui_state_artifact_path,
)

__all__ = [
    "ACTION_CLICK",
    "ACTION_DOUBLE_CLICK",
    "ACTION_HOTKEY",
    "ACTION_SCROLL",
    "ACTION_TYPE",
    "ACTION_WAIT",
    "COORDINATE_TYPE_NORMALIZED",
    "COORDINATE_TYPE_SCREENSHOT_PIXEL",
    "SOURCE_MERGED",
    "SOURCE_OCR",
    "SOURCE_UIA",
    "SOURCE_VLM_VISUAL",
    "SUPPORTED_EXECUTOR_ACTION_TYPES",
    "ActionResult",
    "ActionResultSchemaError",
    "DocumentRegionSummary",
    "HEALTH_DEGRADED",
    "HEALTH_HEALTHY",
    "HEALTH_UNHEALTHY",
    "QUALITY_GOOD",
    "QUALITY_DEGRADED",
    "QUALITY_POOR",
    "COVERAGE_NONE",
    "COVERAGE_PARTIAL",
    "COVERAGE_ADEQUATE",
    "FLAG_OCR_SPARSE",
    "FLAG_OCR_LOW_CONFIDENCE",
    "FLAG_UIA_SHELL_DOMINATED",
    "FLAG_UIA_EMPTY",
    "FLAG_NO_SEARCH_TARGET",
    "FLAG_NO_INPUT_TARGET",
    "FLAG_NO_CLICKABLE",
    "FLAG_ALL_SHELL",
    "FLAG_CANDIDATE_GAP",
    "FALLBACK_USE_VLM_VISUAL",
    "FALLBACK_USE_UIA_ONLY",
    "FALLBACK_USE_OCR_ONLY",
    "FALLBACK_RETRY_WITH_REFOCUS",
    "FALLBACK_NONE",
    "PageSummary",
    "PageSemantics",
    "PageSemanticsError",
    "PerceptionHealth",
    "ScreenMeta",
    "UICandidate",
    "UIState",
    "UISchemaError",
    "bbox_center",
    "candidate_from_ocr",
    "candidate_from_uia",
    "offset_bbox",
    "resolve_click_point",
    "action_result_from_exception",
    "save_ui_state_json",
    "save_screen_meta_json",
    "screen_meta_artifact_path",
    "ui_state_artifact_path",
    "utc_now",
    "GOAL_PROGRESS_ACHIEVED",
    "GOAL_PROGRESS_BLOCKED",
    "GOAL_PROGRESS_IN_PROGRESS",
    "GOAL_PROGRESS_NEAR_GOAL",
    "GOAL_PROGRESS_NOT_STARTED",
    "GOAL_PROGRESS_UNKNOWN",
]
